#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authentication.LoginRequest" do
    optional :user_name, :string, 1
    optional :password, :string, 2
    optional :client_id, :string, 3
  end
  add_message "authentication.LoginReply" do
    optional :result, :bool, 1
  end
end

module Authentication
  LoginRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("authentication.LoginRequest").msgclass
  LoginReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("authentication.LoginReply").msgclass
end
