#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authentication_service.proto for package 'authentication'

require 'grpc'
require 'authentication_service_pb'
#require 'oc_services_pb'

module Authentication
  module Login
    # The Login service definition.
    #class Service < Telemetry::OpenConfigTelemetry::Service
    class Service

      include GRPC::GenericService
      #extend Telemetry::OpenConfigTelemetry

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'authentication.Login'
      #rpc :telemetrySubscribe, Telemetry::SubscriptionRequest, stream(Telemetry::OpenConfigData)

      rpc :LoginCheck, LoginRequest, LoginReply
    end

    Stub = Service.rpc_stub_class
  end
end
