#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "telemetry.SubscriptionRequest" do
    optional :input, :message, 1, "telemetry.SubscriptionInput"
    repeated :path_list, :message, 2, "telemetry.Path"
    optional :additional_config, :message, 3, "telemetry.SubscriptionAdditionalConfig"
  end
  add_message "telemetry.SubscriptionInput" do
    repeated :collector_list, :message, 1, "telemetry.Collector"
  end
  add_message "telemetry.Collector" do
    optional :address, :string, 1
    optional :port, :uint32, 2
  end
  add_message "telemetry.Path" do
    optional :path, :string, 1
    optional :filter, :string, 2
    optional :suppress_unchanged, :bool, 3
    optional :max_silent_interval, :uint32, 4
    optional :sample_frequency, :uint32, 5
  end
  add_message "telemetry.SubscriptionAdditionalConfig" do
    optional :limit_records, :int32, 1
    optional :limit_time_seconds, :int32, 2
  end
  add_message "telemetry.SubscriptionReply" do
    optional :response, :message, 1, "telemetry.SubscriptionResponse"
    repeated :path_list, :message, 2, "telemetry.Path"
  end
  add_message "telemetry.SubscriptionResponse" do
    optional :subscription_id, :uint32, 1
  end
  add_message "telemetry.OpenConfigData" do
    optional :system_id, :string, 1
    optional :component_id, :uint32, 2
    optional :sub_component_id, :uint32, 3
    optional :path, :string, 4
    optional :sequence_number, :uint64, 5
    optional :timestamp, :uint64, 6
    repeated :kv, :message, 7, "telemetry.KeyValue"
  end
  add_message "telemetry.KeyValue" do
    optional :key, :string, 1
    oneof :value do
      optional :double_value, :double, 5
      optional :int_value, :int64, 6
      optional :uint_value, :uint64, 7
      optional :sint_value, :sint64, 8
      optional :bool_value, :bool, 9
      optional :str_value, :string, 10
      optional :bytes_value, :bytes, 11
    end
  end
  add_message "telemetry.CancelSubscriptionRequest" do
    optional :subscription_id, :uint32, 1
  end
  add_message "telemetry.CancelSubscriptionReply" do
    optional :code, :enum, 1, "telemetry.ReturnCode"
    optional :code_str, :string, 2
  end
  add_message "telemetry.GetSubscriptionsRequest" do
    optional :subscription_id, :uint32, 1
  end
  add_message "telemetry.GetSubscriptionsReply" do
    repeated :subscription_list, :message, 1, "telemetry.SubscriptionReply"
  end
  add_message "telemetry.GetOperationalStateRequest" do
    optional :subscription_id, :uint32, 1
    optional :verbosity, :enum, 2, "telemetry.VerbosityLevel"
  end
  add_message "telemetry.GetOperationalStateReply" do
    repeated :kv, :message, 1, "telemetry.KeyValue"
  end
  add_message "telemetry.DataEncodingRequest" do
  end
  add_message "telemetry.DataEncodingReply" do
    repeated :encoding_list, :enum, 1, "telemetry.EncodingType"
  end
  add_enum "telemetry.ReturnCode" do
    value :SUCCESS, 0
    value :NO_SUBSCRIPTION_ENTRY, 1
    value :UNKNOWN_ERROR, 2
  end
  add_enum "telemetry.VerbosityLevel" do
    value :DETAIL, 0
    value :TERSE, 1
    value :BRIEF, 2
  end
  add_enum "telemetry.EncodingType" do
    value :UNDEFINED, 0
    value :XML, 1
    value :JSON_IETF, 2
    value :PROTO3, 3
  end
end

module Telemetry
  SubscriptionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.SubscriptionRequest").msgclass
  SubscriptionInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.SubscriptionInput").msgclass
  Collector = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.Collector").msgclass
  Path = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.Path").msgclass
  SubscriptionAdditionalConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.SubscriptionAdditionalConfig").msgclass
  SubscriptionReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.SubscriptionReply").msgclass
  SubscriptionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.SubscriptionResponse").msgclass
  OpenConfigData = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.OpenConfigData").msgclass
  KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.KeyValue").msgclass
  CancelSubscriptionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.CancelSubscriptionRequest").msgclass
  CancelSubscriptionReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.CancelSubscriptionReply").msgclass
  GetSubscriptionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.GetSubscriptionsRequest").msgclass
  GetSubscriptionsReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.GetSubscriptionsReply").msgclass
  GetOperationalStateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.GetOperationalStateRequest").msgclass
  GetOperationalStateReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.GetOperationalStateReply").msgclass
  DataEncodingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.DataEncodingRequest").msgclass
  DataEncodingReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.DataEncodingReply").msgclass
  ReturnCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.ReturnCode").enummodule
  VerbosityLevel = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.VerbosityLevel").enummodule
  EncodingType = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.EncodingType").enummodule
end
